spring.application.name=kafka-camel-order-processing
server.port=8080

kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP:order-integration}
kafka.consumer.auto-offset-reset=${KAFKA_AUTO_OFFSET_RESET:earliest}
kafka.consumer.consumers=${KAFKA_CONSUMERS:10}

downstream.endpoint-url=${DOWNSTREAM_ENDPOINT_URL:http://localhost:8080/mock/downstream/orders}
downstream.auth-enabled=${DOWNSTREAM_AUTH_ENABLED:false}
downstream.max-concurrency=${DOWNSTREAM_MAX_CONCURRENCY:10}
downstream.queue-size=${DOWNSTREAM_QUEUE_SIZE:2000}

oauth2.token-uri=${OAUTH2_TOKEN_URI:}
oauth2.client-id=${OAUTH2_CLIENT_ID:}
oauth2.client-secret=${OAUTH2_CLIENT_SECRET:}
oauth2.scope=${OAUTH2_SCOPE:}
oauth2.client-auth-method=${OAUTH2_CLIENT_AUTH_METHOD:client_secret_basic}

retry.max-redeliveries=${RETRY_MAX_REDELIVERIES:3}
retry.delay-ms=${RETRY_DELAY_MS:1000}


logging.level.org.apache.camel=INFO
logging.level.com.example.orderintegration=INFO
